### ISSUE TITLE
Syntax highlighting issue for Example 23.2: How Not To List Requirements

### ISSUE THREAD

**Issue by mxdmedia** [feldroy/two-scoops-of-django-3.x#101]
## Location within the Book
23.7.2, Example 23.2: How Not To List Requirements

## Description 
It looks like your pip packages box is using the python text highlighting plugin.  Thus, `#egg=py-jnk` is being highlighted as if it was a comment, rather than being part of the github url.

## Possible Solutions
Don't use python syntax highlighting for this box.

## Your full name so we can provide accurate credit within the book
Mark Dobossy

**Comment by pydanny** [comment]
🚢 🍨
