### ISSUE TITLE
Typo: chapter 18 section 1: acces

### ISSUE THREAD

**Issue by tonykyriakidis** [feldroy/two-scoops-of-django-3.x#105]
## Location within the Book

* Chapter: 18
* Section: 1
* Subsection: -

## Description 
There is a list after the table and the second list item has a typo:

> Much like with a REST API, common **acces** patterns can still be identified and han- dled better through caching, indexing, or code optimization.

## Possible Solutions
Much like with a REST API, common **access** patterns can still be identified and han- dled better through caching, indexing, or code optimization.

## Your full name so we can provide accurate credit within the book
Antonis Kyriakidis

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. 
🚢 🧀
