### ISSUE TITLE
Typo "linkdiff" in 28.9.4 Beware Unusual JavaScript

### ISSUE THREAD

**Issue by lapinvert** [feldroy/two-scoops-of-django-3.x#106]
## Location within the Book

* Chapter or Appendix: 28.9.4 Beware Unusual JavaScript

## Description 

Within the warning section: 
> The URL that **linkdiff**https://feld.to/unusual-javascriptfeld.to/unusual-javascript
links to

## Possible Solutions

Delete the string "linkdiff"

**Comment by pydanny** [comment]
🚢 🍨
