### ISSUE TITLE
templates directory missing in example 4.1 in section 4.4.1

### ISSUE THREAD

**Issue by mathemaat** [feldroy/two-scoops-of-django-3.x#108]
## Location within the Book

* Subsection 4.4.1 Common App Modules

## Description 

Example 4.1 provides a list of common app modules. I would expect to see the `templates` directory in the folder list too.

## Possible Solutions

Add `templates` inside the graphic, directly above `templatetags`.

**Comment by pydanny** [comment]
Typically apps inside a project don't have their own `templates` directories. That only applies to third-party packages.

**Comment by mathemaat** [comment]
Ah, so you're saying that all templates go in the `templates` directory inside the `<django_project_root>` as is indicated in section 3.3? I can see why you would want to do that.

But aren't `views` and `forms` intricately linked with templates? Why is it different for those two files?

Perhaps I need to give it some more thought, or try it out in practice before it all becomes clear.
