### ISSUE TITLE
Incorrect link to Qualys SSL Labs server test

### ISSUE THREAD

**Issue by janfabry** [feldroy/two-scoops-of-django-3.x#110]
## Location within the Book

* Chapter or Appendix: 28: Security best practices
* Section: 28.6: HTTPS Everywhere
* Subsection: 28.6.3: HTTPS Configuration tools

## Description 

> Once you have a server set up (preferably a test server), use the Qualys SSL Labs server test at `ssl-config.mozilla.org` to see how well you did.

## Possible Solutions

The URL should be https://www.ssllabs.com/ssltest/index.html.

The Mozilla link could be used in the previous paragraph:

> Mozilla provides a SSL configuration generator at the `mozilla.github.io/ server-side-tls/ssl-config-generator/`, which can provide a starting point for your own configuration.

This mozilla.github.io URL redirects to the ssl-config.mozilla.org URL.

## Related issue

twoscoops/two-scoops-of-django-1.11#144, fixed on May 2nd. My PDF of 3.x is dated 2020-07-09, so it seems it contains an incorrect fix?

## Your full name so we can provide accurate credit within the book

Jan Fabry

**Comment by pydanny** [comment]
🚢 🍨
