### ISSUE TITLE
Suggestion: Take a look at python-decouple to maintain the environment variable.

### ISSUE THREAD

**Issue by rakibulislam01** [feldroy/two-scoops-of-django-3.x#118]
## Location within the Book

* Chapter or Appendix: 5
* Section: 5.3

## Description 
**[Python-decouple](https://pypi.org/project/python-decouple/)** that deal very well and in an elegant way with settings and secrets. You can easily maintain your environment variable using this. 
[https://pypi.org/project/python-decouple/](url). 
> Python Decouple: Decouple helps you to organize your settings so that you can change parameters without having to redeploy your app.
1. store parameters in ini or .env files;
2. define comprehensive default values;
3. properly convert values to the correct data type;
4. have only one configuration module to rule all your instances.
```
from decouple import config

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
```

**Comment by pydanny** [comment]
🚢
