### ISSUE TITLE
Typo in 6.7

### ISSUE THREAD

**Issue by nlipsyc** [feldroy/two-scoops-of-django-3.x#119]
## Location within the Book

* Chapter or Appendix: 6
* Section: 7
* Subsection: None

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line

Bullet #2, "the reviewed project's average rating"

## Possible Solutions
Judging from the property name, it looks like this was supposed to read "the reviewed product's average rating".

## Your full name so we can provide accurate credit within the book
Noah Lipsyc

**Comment by pydanny** [comment]
🚢
