### ISSUE TITLE
Consider adding django-stronghold

### ISSUE THREAD

**Issue by luzfcb** [feldroy/two-scoops-of-django-3.x#124]
When we develop systems and not public websites, we always want that almost every page needs authentication to be accessed, but the fact that developers can make mistakes and forget to include `login_required` or `LoginRequiredMixin` on some views can often be dangerous in terms of security. 

The `django-stronghold` tries to solve this problem by following the same logic used in many firewalls: Everything is blocked by default (that is, required authentication) and the things that must be accessible and public must be explicitly defined.

https://github.com/mgrouchy/django-stronghold

For the project that uses django-allauth:

https://github.com/mgrouchy/django-stronghold/issues/71#issuecomment-694722097

Note: I don't know what level of compatibility with Django> = 3.0

**Comment by pydanny** [comment]
:ship:
