### ISSUE TITLE
Foreword misspelled

### ISSUE THREAD

**Issue by forthfan** [feldroy/two-scoops-of-django-3.x#125]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile.

Notes:

- TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.
- `??:??` are references for areas written but still being examined by our reviewers and not yet in the published version of the book. Reporting them **doesn't** qualify as an attributable item.

## Location within the Book

* Chapter or Appendix: Foreword
* Section:
* Subsection: page xxv

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

"Forward" should be spelled "Foreword" here and in the Table of Contents.

## Your full name so we can provide accurate credit within the book

Bill Beal

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. 😄 
🚢 🧀
