### ISSUE TITLE
Sentence fragment

### ISSUE THREAD

**Issue by forthfan** [feldroy/two-scoops-of-django-3.x#129]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile.

Notes:

- TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.
- `??:??` are references for areas written but still being examined by our reviewers and not yet in the published version of the book. Reporting them **doesn't** qualify as an attributable item.

## Location within the Book

* Chapter or Appendix: Ch. 28
* Section: 28.22
* Subsection: 2nd paragraph

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

The second sentence is a sentence fragment: "A value that is either sent to your personal phone number or is reset every thirty seconds."

## Possible Solutions

Join the fragment to the previous sentence with a comma: ". . . on your mobile device, a value that is . . ."

## Your full name so we can provide accurate credit within the book

Bill Beal

**Comment by pydanny** [comment]
Instead of combining sentences with a comma, we rewrote the paragraph to describe OTPs.
