### ISSUE TITLE
isort tip is labeled as a regular tip instead of a package tip

### ISSUE THREAD

**Issue by pjbollinger** [feldroy/two-scoops-of-django-3.x#130]
## Location within the Book

* Chapter or Appendix: Chapter 1
* Section: 1.3
* Subsection: `TIP: isort for Sorting Imports`

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

I think the tip box for _isort_ should be a `package tip` rather than a standard `tip`. For a minute, I thought _isort_ was added to the standard library in the latest Python. 😅 

> (In blue) TIP: isort for Sorting Imports

## Possible Solutions

> (In green) PACKAGE TIP: isort for Sorting Imports

## Your full name so we can provide accurate credit within the book

Patrick Bollinger

**Comment by pydanny** [comment]
🚢
