### ISSUE TITLE
typo in 19.1: tradition > traditional

### ISSUE THREAD

**Issue by escalonamm** [feldroy/two-scoops-of-django-3.x#131]
## Location within the Book

* Chapter or Appendix: 19
* Section: 1
* Subsection: Angular

## Description 

> ...the forthcoming Writernaut project demonstrate SPA-like speed and power using tradition HTML templates.

## Possible Solutions

tradition > traditional

## Your full name so we can provide accurate credit within the book

Marcos Escalona

**Comment by pydanny** [comment]
🚢 🍨
