### ISSUE TITLE
typo in 21.3.1:  straigt forward > straightforward

### ISSUE THREAD

**Issue by escalonamm** [feldroy/two-scoops-of-django-3.x#132]
## Location within the Book

* Chapter or Appendix: 21
* Section: 3
* Subsection: 1

## Description 

> Implementing __str__() is straigt forward:

## Possible Solutions

straigt forward > straightforward

https://www.merriam-webster.com/dictionary/straightforward

## Your full name so we can provide accurate credit within the book

Marcos Escalona

**Comment by pydanny** [comment]
🚢 🍨
