### ISSUE TITLE
Possible misspelling in example 14.2 (Chapter 14.3.3, page 182)

### ISSUE THREAD

**Issue by turnovec** [feldroy/two-scoops-of-django-3.x#133]
## Location within the Book

* Chapter or Appendix: 14
* Section: 3
* Subsection: 3

## Description 

```
{% comment %}
List generated via User.objects.all().select_related('flavors')
{% endcomment %}
```
Shouldn't it be "select_related('flavor')" (without the "s" after "flavor")?

## Possible Solutions
```
{% comment %}
List generated via User.objects.all().select_related('flavor')
{% endcomment %}
```

## Your full name so we can provide accurate credit within the book
Marek Turnovec

**Comment by pydanny** [comment]
🚢 🍨
