### ISSUE TITLE
Typo (omission) in 6.2

### ISSUE THREAD

**Issue by scharfmn** [feldroy/two-scoops-of-django-3.x#134]
## 6.2

* Chapter or Appendix: 6
* Section: 2
* Subsection: NA

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

The text says:

> 6.2 Database Migrations
Django comes with a powerful database change propagation library aptly called
“migrations”, or as we prefer to refer to in the book, django.db.migrations.

## Possible Solutions

I think you mean to include a pronoun there: "or as we prefer to refer to _it_ in the book,"

## Your full name so we can provide accurate credit within the book

Michael Scharf - I'm already a contributor via a previous edition. Thank you!

**Comment by pydanny** [comment]
🚢
