### ISSUE TITLE
Omission in 17.3.8

### ISSUE THREAD

**Issue by scharfmn** [feldroy/two-scoops-of-django-3.x#135]
## Location within the Book

* Chapter or Appendix: 17
* Section: 3
* Subsection: 8

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> "We’ve only had to implement customized authentication scheme a few times,"

## Possible Solutions

> "We’ve only had to implement _a_ customized authentication scheme a few times,"

>"We’ve only had to implement customized authentication schemes a few times,"

## Your full name so we can provide accurate credit within the book

Michael Scharf - already credited, thank you !

**Comment by pydanny** [comment]
:ship:
