### ISSUE TITLE
Possible wrong parent class in example 22.9

### ISSUE THREAD

**Issue by kc7wbq** [feldroy/two-scoops-of-django-3.x#136]
## Location within the Book

* Chapter: 22
* Section: 3
* Subsection: 2
* Example 22.9

## Description 
I was trying to follow example 22.9 in chapter 22.3.2 to make typed users. I don't know if I'm confused, or if there is an error in the example. 

Currently:  

    class InventorManager(models.Manager):

When I tried to create a new user in the admin interface I was received the error `AttributeError: 'InventorManager' object has no attribute 'normalize_email'`

## Possible solutions

When I changed the manager to inherit from `BaseUserManager` I was able to add new users: 

    class InventorManager(BaseUserManager):

## Your full name so we can provide accurate credit within the book
Keith Richards (already attributed, thank you)

**Comment by pydanny** [comment]
🚢
