### ISSUE TITLE
https://trygql.com/ is not available anymore

### ISSUE THREAD

**Issue by BasilPH** [feldroy/two-scoops-of-django-3.x#137]
## Location within the Book

* Chapter or Appendix: Chapter 18
* Section: Introduction, before 18.1

## Description 

[trygql.com](https://trygql.com/) doesn't seem to exist anymore. Clicking on the link leads to a 404 page.

## Possible Solutions

- Ideally, the maintainer would get trygql back up again. We might be able to reach out to [Ryan Chenkie](https://twitter.com/ryanchenkie/status/1097919830781583360) on Twitter.
- Replace it with a similar service, although I didn't find one
- Delete the reference

## Your full name so we can provide accurate credit within the book

Basil PHILIPP

**Comment by pydanny** [comment]
🚢
