### ISSUE TITLE
Creating a ModelForm without either `fields` attribute or the `exclude` attribute is prohibited

### ISSUE THREAD

**Issue by kamilturek** [feldroy/two-scoops-of-django-3.x#155]
## Location within the Book

* Chapter or Appendix: 12
* Section: 12.2
* Subsection: Example 12.5

## Description 

Code from example 12.5 presenting definition of `forms.ModelForm` subclass raises `django.core.exceptions.ImproperlyConfigured` exception.

Full exception message:
```
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form FlavorForm needs updating.
```

Explicitly setting fields to use is highly encouraged since Django 1.6 and was fully deprecated in Django 1.8 Please see:
https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#selecting-the-fields-to-use
https://docs.djangoproject.com/en/3.1/releases/1.6/#modelform-without-fields-or-exclude

Other failing examples:
12.10, 12.11, 13.2, 13.4

## Possible Solutions

As both `exclude` and `fields = '__all__'` approaches are discouraged in the book, the only solution is to explicitly specify all fields used in examples mentioned above.

## Your full name so we can provide accurate credit within the book

Kamil Turek

**Comment by pydanny** [comment]
Nice catch! Thanks!
