### ISSUE TITLE
Section 13.1 - broken link

### ISSUE THREAD

**Issue by kamilturek** [feldroy/two-scoops-of-django-3.x#156]
## Location within the Book

* Chapter or Appendix: 13
* Section: 13.1
* Subsection: 13.1 TIP

![image](https://user-images.githubusercontent.com/22010517/112548880-373cd100-8dbd-11eb-89e4-1cb28bd614f7.png)

## Description 

TIP frame contains reference to Django docs section about raising `ValidationError`. However, it points to https://feld.to/2zD4HeB which is broken. The correct one suppose to be https://feld.to/2zd4heb (lowercase version).

## Possible Solutions

Replace broken link with the working one.

## Your full name so we can provide accurate credit within the book

Kamil Turek

**Comment by kamilturek** [comment]
When going through the book I spotted a lot of broken links using the  `feld.to` domain to shorten them. It might be good to check all of them.

**Comment by pydanny** [comment]
Thanks for the advice! We've fixed them globally!
