### ISSUE TITLE
Broken link on 6.1.3

### ISSUE THREAD

**Issue by alifelan** [feldroy/two-scoops-of-django-3.x#162]
## Location within the Book

* Chapter or Appendix: 6
* Section: 1
* Subsection: 3

Edit: Seems to happen on many links, they work until 5.4, afterwards I find shortened links that dont exist. May not be a real issue but a WIP.

## Description 

Django docs link at the end of the chapter (model inheritance) sends to a broken link on your site.

## Your full name so we can provide accurate credit within the book

Ali Felan

**Comment by pydanny** [comment]
Fixed! thanks!
