### ISSUE TITLE
Broken Link 6.1.3

### ISSUE THREAD

**Issue by abdulwahidgul24085** [feldroy/two-scoops-of-django-3.x#165]
## Location within the Book

* Chapter or Appendix: 6 Models Best Practices 
* Section: 6.1.3 
* Subsection: Model Inheritance in Practice: The TimeStampedModel

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

➤ docs.djangoproject.com/en/3.2/topics/db/models/#model-inheritance This link routes to  https://feld.to/3csJP7U and the field link is broken.

## Possible Solutions
Fix the Feld Link
## Your full name so we can provide accurate credit within the book
abdulwahid gul

**Comment by pydanny** [comment]
Fixed! Thanks!
