### ISSUE TITLE
Link 404 in 1.2.0 and 1.2.1

### ISSUE THREAD

**Issue by xavdid** [feldroy/two-scoops-of-django-3.x#167]
## Location within the Book

* Chapter or Appendix: 1
* Section: 1.2 
* Subsection: 1.2.0 and 1.2.1

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

A few links are 404ing, likely because the Netlify slugs only work for lowercase slugs. Here's a table:

| linked text in book | current (404) destination | should be |
| --- | --- | --- |
|`python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the- hobgoblin-of-little-minds`|`https://feld.to/2y01SnH`|`https://feld.to/2y01snh`|
|`python.org/dev/peps/pep-0008/#maximum-line-length`|`https://feld.to/2YgG6Xs`|`https://feld.to/2ygg6xs`|

## Your full name so we can provide accurate credit within the book

David Brownman (my site is https://xavd.id if that can be included)

**Comment by pydanny** [comment]
Fixed globally with a regular expression, thanks! 😄
