### ISSUE TITLE
Broken link on 22.3.4 

### ISSUE THREAD

**Issue by ionescu77** [feldroy/two-scoops-of-django-3.x#170]
## Location within the Book

* Subsection:

22.3.4

## Description 

Following paragraph includes a 404 link.

> Vitor Freitas’ of ‘Simple is better than Complex article’ on the topic of  multiple user types. Very useful article, even if he doesn’t use proxy models:  feld.to/2VSi3My

## Possible Solutions

Chech mapping of url shortener:

feld.to/2VSi3My

The linked article seems to be here:

https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html

**Comment by pydanny** [comment]
Fixed globally with a regular expression, but thanks! 😄
