### ISSUE TITLE
Wrong Embedded Link

### ISSUE THREAD

**Issue by hannody** [feldroy/two-scoops-of-django-3.x#172]
## Location within the Book

* Chapter or Appendix: 17 Building REST APIs With Django REST Framework
* Section: 17.7 
* Subsection: 2 Provide Client SDKs

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
Within the first bulleted list item "Command line client" there is a link and #text/tag that both have wrong embedded link (i.e.https://feld.to/3hmDGOb) that lands on "page not found"
 
![Screenshot from 2021-06-14 09-59-26](https://user-images.githubusercontent.com/7309693/121830286-4023ab80-ccf7-11eb-91d1-a1ea9afdbb2b.png)

## Possible Solutions
Embedded link need to direct to "https://www.django-rest-framework.org/api-guide/schemas/" instead of "https://feld.to/3hmDGOb"

## Your full name so we can provide accurate credit within the book
Mohanad Abu-Nayla

**Comment by pydanny** [comment]
Fixed
