### ISSUE TITLE
Missing apps.py in common App modules Example

### ISSUE THREAD

**Issue by krystofer47** [feldroy/two-scoops-of-django-3.x#177]
## Location within the Book

* Chapter or Appendix: 4
* Section: 4
* Subsection: 1

## Description 

Example 4.1 is missing the apps.py file.

## Possible Solutions

Adding apps.py in Example 4.1

**Comment by pydanny** [comment]
What's your name so we can attribute you?

**Comment by krystofer47** [comment]
Christoph Brosch
