### ISSUE TITLE
Dead link to channels docs

### ISSUE THREAD

**Issue by bullfest** [feldroy/two-scoops-of-django-3.x#18]
## Location within the Book

* Chapter or Appendix: Appendix H
* Section: (not numbered) Watch Out For Spaghetti Code

## Description 
Dead link to https://channels.readthedocs.io/en/stable/testing.html

## Possible Solutions
Should link to https://channels.readthedocs.io/en/stable/topics/testing.html

**Comment by pydanny** [comment]
🚢 🍨
