### ISSUE TITLE
Typo and wrong link in Appendix C

### ISSUE THREAD

**Issue by JeanLevasseur** [feldroy/two-scoops-of-django-3.x#181]
## Location within the Book

* Appendix C: Additional Resources

### Wrong link

* awesome-jango.com link redirect to https://www.mayan-edms.com which does not seems to be Django related.

### Typo

* testdrivei.io testdriven.io/blog/topics/django/ should read: testdriven.io testdriven.io/blog/topics/django/

## Your full name so we can provide accurate credit within the book
Jean Levasseur

Kind regards for the great book!!

**Comment by issacsapple** [comment]
Hi. I'm the new maintainer of Awesome Django. I've been granted permissions from the original author to continue the project. The domain awesome-django.com has been updated to reflect this. Thanks!
