### ISSUE TITLE
Missing schema in link to cdrf.co

### ISSUE THREAD

**Issue by bullfest** [feldroy/two-scoops-of-django-3.x#19]
## Location within the Book

* Chapter or Appendix: 17
* Section: 2
* Subsection: N/A - Inside TIP-box

## Description 
Rendered link ("http://cdrf.co") is correct, but when clicked the schema ("http://") is missing, giving errors in at least some PDF viewers when clicked.

## Possible Solutions
Should probably be the other way around, as most other rendered links in the book don't have schemas, but the target does.

**Comment by pydanny** [comment]
🚢 🍨 

We are showing the HTTP schema because it is not HTTPS. Or is that too confusing? In any case, you are in the acknowledgements now!

**Comment by bullfest** [comment]
Cool! 

It's not really confusing, my suggestion was based on that almost all other printed links don't have a schema regardless if the underlying link uses HTTP or HTTPS. For uniformity's sake I think that it would be nice to decide on one pattern however :smiley:
