### ISSUE TITLE
Reference Pycharm Security Django reference

### ISSUE THREAD

**Issue by tonybaloney** [feldroy/two-scoops-of-django-3.x#20]
## Description

The security chapter could use a reference to the [PyCharm Security](https://pycharm-security.readthedocs.io/en/latest/django.html) project, which has automated checking for Django security pitfalls. The project is free and open-source.

It can be run from PyCharm as an extension, or as a GitHub Action. It will find and highlight pretty-much all of the issues marked in the chapter. Including-

- All of the insecure Django SQL injection holes
- Missing CSRF middleware
- Missing Xframe middleware
- Enabling Debug mode
- Run PyUp.io against the installed packages
- Check for pyyaml and defusedxml usage

**Comment by pydanny** [comment]
Added!
