### ISSUE TITLE
Malcolm Tredinnick memorial page missing

### ISSUE THREAD

**Issue by mikowhy** [feldroy/two-scoops-of-django-3.x#206]
## Location within the Book

* Chapter or Appendix: Dedication
* Section: Dedication
* Subsection: Dedication

## Description 

There is a link to [feldroy.com/pages/malcolm-tredinnick-memorial](feldroy.com/pages/malcolm-tredinnick-memorial) in `Dedication` section

Linked page **DOESN'T exist**

## Possible Solutions

link to proper page - [https://daniel.feldroy.com/posts/memories-of-malcolm](https://daniel.feldroy.com/posts/memories-of-malcolm) ?

## Your full name so we can provide accurate credit within the book

Mikołaj Paczkowski

**Comment by pydanny** [comment]
We rebuilt our online store to reduce costs. I've updated and brought over the page, which can be seen here: https://www.feldroy.com/malcolm-tredinnick-memorial

Thanks for letting us know!
