### ISSUE TITLE
Unresolved references in Tip in 5.5.1

### ISSUE THREAD

**Issue by mfisher911** [feldroy/two-scoops-of-django-3.x#26]
## Location within the Book

* Chapter or Appendix: 5
* Section: 5
* Subsection: 1

## Description 

In "TIP: Using Multiple Requirements Files With PaaS"

> We cover this in **??: ??**

**Comment by pydanny** [comment]
Those reference areas are still under review. We'll put in a notice in our issues and the next update that these will be updated shortly.
