### ISSUE TITLE
Inconcistencies with changelog

### ISSUE THREAD

**Issue by bullfest** [feldroy/two-scoops-of-django-3.x#28]
The [changelog](https://github.com/feldroy/two-scoops-of-django-3.x/blob/master/changelog.md) references a few changes that seems to not be in the book. As the changelog is dated May 10 and the book May 11 I would assume that the changes should be in the book.

Do you want these inconsistencies as issues or is the dating of book and changelog just a bit off?

**Comment by pydanny** [comment]
I think in the mad rush of the last few hours before launch we had a glitch with the changelog. The update sent out later today will correct that.

**Comment by pydanny** [comment]
Should be up-to-date. Please reopen if this is not true.
