### ISSUE TITLE
Django may deprecate NullBooleanField and recommends BooleanField(null=True)

### ISSUE THREAD

**Issue by gtwohig** [feldroy/two-scoops-of-django-3.x#30]
## Location within the Book

* Chapter or Appendix: 6
* Section: 4
* Subsection: 4
6.4.4, Table 6.2 BooleanField row

## Description 

The book says not to use null with BooleanField, and to rather use NullBooleanFields
However, the latest Django docs (https://docs.djangoproject.com/en/3.0/ref/models/fields/#nullbooleanfield) state:
> NullBooleanField
> class NullBooleanField(**options)
> Like BooleanField with null=True. Use that instead of this field as it’s likely to be deprecated in a future version of Django.

## Possible Solutions
Update to say that null=True is Okay

**Comment by pydanny** [comment]
Hey! Thanks for the suggestion, it's going in. Can you give me your full name so I can properly attribute you in the book?

**Comment by gtwohig** [comment]
Sure, Greg Twohig. Thanks :-)
