### ISSUE TITLE
Table 6.2 When To Use Null and Blank by Field is Missing

### ISSUE THREAD

**Issue by Coop56** [feldroy/two-scoops-of-django-3.x#31]
## Location within the Book

* Chapter or Appendix: Chapter 6 Django Model Design
* Section: 6.4
* Subsection: 6.4.4

## Description 

This section appears to be missing the guidance relating to when to use Null and Blank.  It skips right over to the next section after explaining what this section is supposed to be about.

## Possible Solutions

I checked version 1.11 of the book and it appears there used to be a table here, so that's what is missing and needs added back.

**_Edit:_** The table is actually a page down, after the entire next section, so it's still missing from the correct section but does exist.

**Comment by pydanny** [comment]
Yeah, we're having weird bounding box problems with Xelatex we're trying to resolve. This is our primary focus right now.

**Comment by pydanny** [comment]
This has been fixed!
