### ISSUE TITLE
Unnecessary Equals Sign in Django Subreddit Link

### ISSUE THREAD

**Issue by Coop56** [feldroy/two-scoops-of-django-3.x#32]
## Location within the Book

* Chapter or Appendix: 36
* Section: 36.4
* Subsection: 36.4.1 - 10 Easy Ways to Participate

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

There is an unnecessary equals sign in the Django Subreddit link in recommendation 5 of this section.  Clicking the link still works, but if you copy and paste the full URL you'll get an error due to that equals sign being there.

**Comment by pydanny** [comment]
🍨 🚢
