### ISSUE TITLE
8.4.1: wrong example reference

### ISSUE THREAD

**Issue by rescudero** [feldroy/two-scoops-of-django-3.x#33]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile.

## Location within the Book

* Chapter or Appendix: 8
* Section: 4
* Subsection: 1

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line.

8.4.1 Makes for Shorter, More Intuitive, and Don’t Repeat Yourself
URL Names
In **example 8.2** what we don’t see are URL names like “tastings_detail” and
“tastings_results” that copy the model or app name.

## Possible Solutions

I think It should say: **example 8.3**

**Comment by pydanny** [comment]
Thank you!

**Comment by pydanny** [comment]
Can you provide me with your name so I can attribute you correctly in the book?

**Comment by rescudero** [comment]
Hi Daniel / Audrey...
Of course, ir would a honor for me.

My name: Ricardo Escudero Neumann

I'm from Chile, in south américa.. and it would be great for me if I can be
of any help or support for you in this side of the world.

I love your books.

Warm regards.
Ricardo.
