### ISSUE TITLE
Location and content of Table 6.2 when to use null and blank by field

### ISSUE THREAD

**Issue by kakulukia** [feldroy/two-scoops-of-django-3.x#40]
## Location within the Book

* Chapter or Appendix: 6
* Section: 4
* Subsection: 5

## Description 

This table is misplaced in between the warning for "Don't serve files from BinaryField".

## Possible Solutions
It should move up to 6.4.4

======

<img width="602" alt="Bildschirmfoto_2020-05-17_um_08_10_02" src="https://user-images.githubusercontent.com/96352/82137493-07c24d00-9819-11ea-9c88-bd463dbe333c.png">

**ManyToManyField**
As to the content: Its kinda contradictory to say do it and don't do it in the same line. This needs an explanation. :)
Furthermore this table IMHO is only meaningful when the dont's are explained in a form of "Don't do that otherwise this will happen ..".

Reading up on the Django docs "null has no effect since there is no way to require a relationship at the database level." brings even more mystery to why you are telling the user to set or not set null=something?
Whats the issue here? I never had any.

Also this table might be a good reference to find out why only some others are broken.

**Comment by pydanny** [comment]
Thank you for this very thoughtful issue.

**Comment by pydanny** [comment]
Can you provide me with your full name so I can attribute you properly in the book?

**Comment by kakulukia** [comment]
Andy Grabow

**Comment by kakulukia** [comment]
thx
