### ISSUE TITLE
ponycheckup.com (section 28.26) has been shutdown

### ISSUE THREAD

**Issue by sterat** [feldroy/two-scoops-of-django-3.x#41]
The link in 28.26 to ponycheckup.com exists but is just a line to say that the site has been shut down,

**Comment by pydanny** [comment]
🍨 🚢

**Comment by stuartmaxwell** [comment]
Hi - the Pony Checkup site has been revived and is now hosted at https://djcheckup.com. Sasha has kindly given me the domain name for Pony Checkup so the old URL will redirect to the new one. Would be great if you could check out it - the core checking logic has been rewritten and has removed a couple of old bugs.
Cheers - Stuart.
