### ISSUE TITLE
Warning of unmaintained pipenv

### ISSUE THREAD

**Issue by pabu** [feldroy/two-scoops-of-django-3.x#44]
## Location within the Book

* Chapter or Appendix: 2
* Section: 2
* Subsection: 0

## Description 

In info box "WARNING: Be Wary of Pipenv", the reason for staying clear of Pipenv is stated as it not having seen a formal release since late 2018. The project has had 3 github releases the last few weeks so a new pypi release soon seems likely.

## Possible Solutions

Current state may not warrant immediate changes to the book so you could consider this more of a heads for now.

Cheers,
pabu

**Comment by pydanny** [comment]
`GitHub release != PyPI release`

When pipenv has a formal release that matches the rest of the Python world we'll do an evaluation.
