### ISSUE TITLE
straigt forward typo

### ISSUE THREAD

**Issue by gtwohig** [feldroy/two-scoops-of-django-3.x#49]
## Location within the Book

* Chapter or Appendix: 21
* Section: 3
* Subsection: 1

## Description 

> Implementing __str__() is straigt forward:

## Possible Solutions
fix typo `straigt forward` -> `straightforward`

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! 😄 We will be giving attribution in the next update of the book. What name would you like for us to use in order to give you attribution?
🚢 🧀

**Comment by gtwohig** [comment]
Thanks, I go by Greg Twohig.
