### ISSUE TITLE
REST Frameworks Must Come With Rate Limiting but no explaination on how to do it.

### ISSUE THREAD

**Issue by ramast** [feldroy/two-scoops-of-django-3.x#50]
## Location within the Book

* Chapter or Appendix: 17
* Section: 17.6
* Subsection: 17.6.2 REST Frameworks Must Come With Rate Limiting

## Description 

Article stress on importance of  throttling your API but doesn't show how to do it.

## Possible Solutions

The bare minimum is giving link to django rest framework documentation on this regard

https://www.django-rest-framework.org/api-guide/throttling/#setting-the-throttling-policy

**Comment by pydanny** [comment]
What's your full name?

**Comment by ramast** [comment]
Thanks Danny, You've already added me when I posted this issue https://github.com/feldroy/two-scoops-of-django-3.x/issues/35
