### ISSUE TITLE
Installing coreapi would cause ./manage.py generateschema to fail

### ISSUE THREAD

**Issue by ramast** [feldroy/two-scoops-of-django-3.x#51]
## Location within the Book

* Chapter/Section/Subsection: 17.7.2
 
The book didn't discuss DRF schema generation and instead gave some links for further reading.
The very first link is 
django-rest-framework.org/topics/api-clients/
#command-line-client

However installing `coreapi-cli` which would install `coreapi` as a dependency would result in schema generation to fail due to a [bug in DRF](https://github.com/encode/django-rest-framework/issues/6868)

My limited understanding is that DRF is moving away from `coreapi` (which the book heavily advertise) to `openapi`

> We're planning to iteratively work towards OpenAPI becoming the standard schema representation. This will mean that the coreapi dependency will gradually become removed, and we'll instead generate the schema directly, rather than building a CoreAPI Document object.

https://www.django-rest-framework.org/community/3.9-announcement/

## Possible Solutions

I hope the Authors would give some love to that sections because it's very important especially for the "Javascript and Django" chapter. 
At very least please provide better links that focus on openapi instead of coreapi.

**Comment by pydanny** [comment]
Coreapi is pretty much dead. We need to explore modern alternatives. We haven't written a Python-powered client SDK in a few years. We don't know what is the current optimal solution.

**Comment by ramast** [comment]
I've spent some time reading about available implementations of OpenAPI both for Python and Javascript.

I didn't find CLI option for python that would allow me to browse the schema so here is what I found working.


1. Generate Schema in JSON format
-----
./manage.py generateschema  --format="openapi-json" > schema.json

You will need to re-generate the schema anytime you update your API. A git precommit hook can help automating that.

2. Please the schema in an accessible location
-----
For example http://example.com/static/schema.json

3. Use Javascript OpenAPI library to read the schema and give you seamless integration with Django.
I found [OpenAPI Client Axios](https://github.com/anttiviljami/openapi-client-axios) to be simple enough and very handy to use.

It's an extension to Axios so you still benefit from all features of Axios library.

The only cons is that unlike original coreapi library, this one doesn't do any validation. If a field is defined as an integer and you tried to pass a string, it will still pass the parameters to the API and let the error return from backend.

There is other options like swagger but I couldn't figure out to get it to work with OpenAPI 3
