### ISSUE TITLE
django-authtools does not support Django 3

### ISSUE THREAD

**Issue by kc7wbq** [feldroy/two-scoops-of-django-3.x#54]
In page 265 there is a package tip suggesting django-authtools. 

Currently django-authtools does not support Django 3:
https://github.com/fusionbox/django-authtools/issues/107

The issue has been open for 4 months.

**Comment by pydanny** [comment]
Added a warning note to the book.

**Comment by pydanny** [comment]
Also, next time provide chapter, section, and subsection numbers. Page counts change all the time.
