### ISSUE TITLE
recommend functools.cached_property outside of Django

### ISSUE THREAD

**Issue by gtwohig** [feldroy/two-scoops-of-django-3.x#57]
## Location within the Book

* Chapter or Appendix: 31
* Section: 3
* Subsection: 5

## Description 

cahed_property is included in the standard library (functools) starting with Python 3.8. https://docs.python.org/dev/library/functools.html?highlight=s#functools.cached_property 

## Possible Solutions
Change the warning about copying and pasting the code from Django to suggest using the standard lib. I think it is also worth calling out how Django has had a positive impact on the language as well.
Also, is there a reason to use the Django one over the functools one within Django? If there is that would be interesting to understand.

**Comment by pydanny** [comment]
Thanks for reminding us about this development! My own [cached-property](https://pypi.org/project/cached-property/) will turn into a shim. Hooray!

AFAIK, there is no reason to use the Django version instead of Python's STDLB's version.

**Comment by pydanny** [comment]
🚢 🍨

**Comment by pydanny** [comment]
Please provide your full name so we can acknowledge you properly in the book
