### ISSUE TITLE
Missing file layout example

### ISSUE THREAD

**Issue by sdil** [feldroy/two-scoops-of-django-3.x#62]
## Location within the Book

* Chapter or Appendix:
* Section: 4.5.2 The Large Single App Project (page 42)
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line.

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

![image](https://user-images.githubusercontent.com/461537/83619278-3df42080-a5be-11ea-8d62-e14b326e3f6b.png)

Todo layout is not present

**Comment by pydanny** [comment]
Thank you for submitting this issue. However, per the issue template:

> TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.
