### ISSUE TITLE
Section 1.4 needs updating for python 3

### ISSUE THREAD

**Issue by sterat** [feldroy/two-scoops-of-django-3.x#64]
## Location within the Book

Section 1.4  -  Use Explicit Relative Imports

## Description 
This section looks like the code has been updated for python 3 but not the text.

The code examples that are described as 'implicit relative' are actually absolute imports, apart from the one in Table 1.1 which is correct.

Implicit relative imports are not part of python3 and therefore cannot be used in django 3.x.

## Possible Solutions
Replace every mention of implicit relative with absolute, then decide if the result is what you really want to say.

If you want to say that absolute imports are bad, then you need to say why the absolute imports from core.views are ok.

Perhaps remove Table 1.1 since in python 3 there is no complexity that needs explaining.

**Comment by pydanny** [comment]
🚢 🍨
