### ISSUE TITLE
Typo in 5.3 "Separate Configuration From Code"

### ISSUE THREAD

**Issue by lancegoyke** [feldroy/two-scoops-of-django-3.x#68]
## Location within the Book

* Chapter: 5
* Section: 3
* Subsection: 0

## Description 

There's a small typo in the TIP box "12 Factor App: Store Config in the Environment".

> Some developers even advocate combining the use of environment variables with a single settings ***modules***.

## Possible Solutions

> Some developers even advocate combining the use of environment variables with a single settings ***module***.

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. 😄 
🚢 🧀
