### ISSUE TITLE
Potential Unsupported Claim of django-admin over manage.py

### ISSUE THREAD

**Issue by lancegoyke** [feldroy/two-scoops-of-django-3.x#69]
## Location within the Book

* Chapter: 5
* Section: 3
* Subsection: 5

## Description 

In the tip box titled "TIP: Using django-admin Instead of manage.py", you mention...

> The official Django documentation says that you should use django-admin rather than manage.py when working with multiple settings files: docs.djangoproject.com/en/3.0/ref/django-admin/

I clicked the link, skimmed the page, and cycled through all the "django-admin" and "manage.py" occurrences, but I couldn't find such a recommendation. Maybe I missed it? Or maybe it was for an older version's docs?

**Comment by pydanny** [comment]
Thank you for identifying this, it does appear that the Django docs have changed!

**Comment by pydanny** [comment]
🚢 🧀
