### ISSUE TITLE
Suggestion: Give small note on how to add tags to git repo

### ISSUE THREAD

**Issue by ramast** [feldroy/two-scoops-of-django-3.x#71]
## Location within the Book

* Chapter or Appendix: 23
* Section: 12
* Subsection: 3

## Description 

Add small note on how to use git tags

To add tag

     git tag -a v1.4 -m "my version 1.4"

To view tag

     git show v1.4

To push tag to repo

    git push origin v1.4

Or simply link to [Git Documentation](https://git-scm.com/book/en/v2/Git-Basics-Tagging)

**Comment by pydanny** [comment]
Great advice!

🚢 🍨
