### ISSUE TITLE
Sugestion: Use url namespaces in the Testing chapter

### ISSUE THREAD

**Issue by ramast** [feldroy/two-scoops-of-django-3.x#72]
## Location within the Book

* Chapter or Appendix: 24
* Section: 3
* Subsection: 1

## Description 

The book recommend using url namespaces ( Section 8.4 Use URL Namespaces )
However it doesn't use url namespaces in the example test code

     self.create_read_url = reverse('flavor_rest_api')

instead of

     self.create_read_url = reverse('flavors:flavor_rest_api')

**Comment by pydanny** [comment]
🚢 🍨
