### ISSUE TITLE
Blog post changed or description is wrong

### ISSUE THREAD

**Issue by sean-wallace** [feldroy/two-scoops-of-django-3.x#73]
## Location within the Book

* Chapter or Appendix: 6
* Section: 7
* Subsection: 1

## Description 

The second bullet of in this subsection is a link to a [medium.com post](http://medium.com/eshares-blog/supercharging-django-productivity-8dbf9042825e) with the note that it

> Includes a really good section on using DateTimeField for logical deletes.

This article doesn't seem to mention or use DateTimeField at all, at least not in its current form.

## Possible Solutions

Change the comment? Or change the link?

**Comment by pydanny** [comment]
Whoa! They changed it! It was such a nice solution too!

🚢 🍨
