### ISSUE TITLE
Example 17.10: Import of wrong module (url instead of path)

### ISSUE THREAD

**Issue by hrother** [feldroy/two-scoops-of-django-3.x#75]
## Location within the Book

* Chapter or Appendix: 17
* Section: 3
* Subsection: 5

* Example 17.10

Build: TSD3x-2020-06-16-alpha

## Description 

The example imports

``` python
from django.conf.urls import url
```
but uses ``path``

``` python
urlpatterns = [
    # {% url 'api:flavors' %}
    path(
        route='flavors/',
        view=flavor_views.FlavorCreateReadView.as_view(),
        name='flavors'
    ),
...
]
```

## Possible Solutions

Import ``path`` instead of ``url``

```python
from django.urls import path
```

in example 17.10.

**Comment by pydanny** [comment]
🚢 🍨
