### ISSUE TITLE
Variable name in CamelCase

### ISSUE THREAD

**Issue by ramast** [feldroy/two-scoops-of-django-3.x#76]
## Location within the Book

* Chapter or Appendix: 31
* Section: 5
* Example: 31.10

## Description 

In the following code:

     JSONSerializer = get_serializer('json')

A varaiable has a CamelCase naming style because - understandably - it's holding a class definition. 
I like it and it make sense to me but I just need to be absolutely sure that this is correct.

I've checked [PEP](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) in this regard and it says

> Function names should be lowercase, with words separated by underscores as necessary to improve readability.

> Variable names follow the same convention as function names.

> mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

So does that mean this code violate PEP rules?

**Comment by pydanny** [comment]
Since what is being loaded is a Class, not a variable, we believe it is better suite to stay as it is. Otherwise people may attempt to call JSONSerializer as a function, when it is a class.

**Comment by ramast** [comment]
Got it, Thank you!
