### ISSUE TITLE
possible typo: "intentially"

### ISSUE THREAD

**Issue by znalo** [feldroy/two-scoops-of-django-3.x#77]
## Location within the Book

* Chapter 19 Javascript and Django
* Section: 1 Popular JavaScript appoaches
* Subsection: Small, Focused Libraries + Vanilla JavaScript
Bullet point: Alpine.js

## Description 

Bullet point: Alpine.js:
> "The syntax is intentially almost identical to Vue"

## Possible Solutions
intentially? Intentionally?

I should add it is a cool word and arguably should be introduced to the language if it hasn't already, so maybe not a bug, especially if was intentially done.

**Comment by pydanny** [comment]
I will submit intentially to the authorities! ha ha 

🚢 🍨
