### ISSUE TITLE
`allow_tags` was deprecated in django 1.9

### ISSUE THREAD

**Issue by tim-mccurrach** [feldroy/two-scoops-of-django-3.x#78]
## Greetings! 

Firstly, thankyou both for taking the time to write this book. I'm really enjoying reading, and learning from it :) 

## Location within the Book

* Chapter 21: Working With the Django Admin
* Section: 21.4 Adding Callables to ModelAdmin Classes

## Description 

In Example 21.4  (Adding Callables to ModelAdmin Classes), you add the following code:
```
# Displays HTML tags
# Never set allow_tags to True against user submitted data!!!
show_url.allow_tags = True
```
I was a little confused as to why this was necessary since you had used `format_html` a few lines earlier. Googling, I found that `allow_tags` was actually deprecated back in version 1.9 (see [release notes](https://docs.djangoproject.com/en/3.0/releases/1.9/#id1) ). Indeed searching the `contrib.admin` directory I found no instances of `allow_tags` so it would appear the additional lines quoted above actually do nothing at all.

At the end of this section there is a warning about when it is safe to use `allow_tags`, which is misleading and could lead to a security issue!!
 
## Possible Solutions

The warning section could be replaced with a warning about always using `format_html` when adding user-entered data via a readonly field, or a reference to your chapter on security. As things stand, it gives the impression that so long as `allow_tags` is `False` then you can add whatever you want. Combining this with misuse of `mark_safe` could lead to serious security ramifications.

**Comment by pydanny** [comment]
Thanks for this awesome ticket! 

🚢 🧀
