### ISSUE TITLE
View Mixins have no need to inherit from python `object`

### ISSUE THREAD

**Issue by lapinvert** [feldroy/two-scoops-of-django-3.x#81]
Hi there,

Within, `10.2 Using Mixins With CBVs` or more specifically page 123, we have:

- `3: Mixins should inherit from Python’s built-in object type.`
- And a little bit later again a reference to that: `Finally, FreshFruitMixin inherits from object (rule 3).`

However, `FreshFruitMixin` in the code sample **is not inheriting** from `object`.

I think that changing it to `class FreshFruitMixin(object)` as it was already the case in earlier versions of the book (`1.6` for example), is not a solution as this rule of inheriting from `object` seems quite uncommon. It bothered me at the time of reading `1.6` as well because we do not see that in Django docs, and there is very few results about that practice on the web.

My guess is that the sample code `class FreshFruitMixin:` is correct and the rule about inheriting from `object` is the one that should be removed.

**Comment by pydanny** [comment]
Nice catch! Wow! We'll get that updated ASAP!

**Comment by pydanny** [comment]
🚢 🍨
