### ISSUE TITLE
Inventor with the right manager

### ISSUE THREAD

**Issue by kakulukia** [feldroy/two-scoops-of-django-3.x#83]
## Location within the Book

* Chapter or Appendix: 22
* Section: 3
* Subsection: 2

Example 22.9

## Description 
is
```
class Inventor(User):
    ...
    objects = EaterManager()
```

but shoud be
```
class Inventor(User):
    ...
    objects = InventorManager()
```

## Your full name so we can provide accurate credit within the book
already done

**Comment by pydanny** [comment]
🚢 🍨
