### ISSUE TITLE
typo 22.3.2

### ISSUE THREAD

**Issue by kakulukia** [feldroy/two-scoops-of-django-3.x#84]
## Location within the Book

* Chapter or Appendix: 22
* Section: 3
* Subsection: 2

After Example 22.9

## Description 

> What do create is references to a model object on which we can hang custom managers, methods, and properties.

## Possible Solutions

An added they, as this sounds weird.

What they do create is references to a model object on which we can hang custom managers, methods, and properties.

## Your full name so we can provide accurate credit within the book
done

**Comment by pydanny** [comment]
🚢 🍨
