### ISSUE TITLE
Typo: "Looser coupling" (well, that was funny)

### ISSUE THREAD

**Issue by lapinvert** [feldroy/two-scoops-of-django-3.x#86]
## Location within the Book

* 4.5.1 Service Layers
* Page 39 (2020-06-16 version)

## Description 

> "Looser coupling means ..."

-> Must be replaced by "Loose coupling".

I wish we had that word tho.

## Your full name so we can provide accurate credit within the book

it's in my profile!

**Comment by pydanny** [comment]
🚢 🍨
