### ISSUE TITLE
"EaterManager" should be "InventorManager" in example 22.9

### ISSUE THREAD

**Issue by kc7wbq** [feldroy/two-scoops-of-django-3.x#87]
## Location within the Book

* Chapter 22
* Section: 3
* Subsection: 2
* Example 22.9

## Description 

I think there is a typo in example 22.9. The example is about Inventors, but there is a reference to an EaterManger class. 
```
# Ensures queries on the Inventor model return only Inventors
objects = EaterManager()
```

## Possible Solutions
Change `EaterManager` to `InventorManager`

## Your full name so we can provide accurate credit within the book
Keith Richards (My name is already listed, thank you)

**Comment by pydanny** [comment]
🚢 🍨
