### ISSUE TITLE
MacOS switched from bash to zsh in Catalina as the default shell

### ISSUE THREAD

**Issue by xyvs** [feldroy/two-scoops-of-django-3.x#89]
## Location within the Book

* Chapter or Appendix: 5
* Section: 3
* Subsection: 2

## Description 

Since Catalina, MacOS switched from bash to zsh by default, the shell config file isn't `.bashrc` anymore, the new config file for zsh is `.zshrc` which it's not listed and might be hepful from some users to add it.

## Possible Solutions

Add `.zshrc` to the examples listed already and maybe add a comment about the switch to zsh in recent versions of MacOS.

## Your full name so we can provide accurate credit within the book

José Francisco Martínez Salgado

**Comment by pydanny** [comment]
🚢 🍨
