### ISSUE TITLE
Reference to adding indexes coming up before actually introducing this concept

### ISSUE THREAD

**Issue by lapinvert** [feldroy/two-scoops-of-django-3.x#90]
## Location within the Book

* Chapter or Appendix: 6.9 Summary
* Page 82 (version 2020-06-16-alpha)

## Description 
We have this in the summary:
> Don’t forget to use indexes. Add indexes when you have a better feel for how you’re using data throughout your project.

But indexes are introduced only later, at 7.6.

## Possible Solutions

Move it to the summary of section 7

## PS

It was already the case in Two Scoops 1.11 :)

**Comment by pydanny** [comment]
🚢 🍨
