### ISSUE TITLE
Minor improvement: coding consistency on 9.5 and 9.6 examples

### ISSUE THREAD

**Issue by lapinvert** [feldroy/two-scoops-of-django-3.x#91]
## Location within the Book

* Chapter or Appendix: 9.3 Decorators are sweet
* Page 117 (version 2020-06-16-alpha)

## Description 

Example 9.5 uses syntax `import  functools` then `@functools.wraps(view_func)`
while example 9.6 uses syntax `from functools import wraps` then `@wraps(view_func)`

## Possible Solutions

Use `from functools import wraps` / `@wraps` on 9.5.
Django source code uses this syntax as well: https://docs.djangoproject.com/en/3.0/_modules/django/utils/decorators/

## Update

The TIP box that comes just after "TIP: What About functools.wraps()?" should be updated accordingly, which means actually the quickest way to regain consistency might be to change the 9.6 example to make it use `functools.wraps()`.

**Comment by pydanny** [comment]
🚢 🍨
