### ISSUE TITLE
Github's 400 page is not self contained

### ISSUE THREAD

**Issue by lapinvert** [feldroy/two-scoops-of-django-3.x#94]
## Location within the Book

* Chapter or Appendix: 14.8 Error Page Templates
* Page: 192-193 (version 2020-07-09 aplha)

## Description 

"All CSS styles are inline in the head of the same HTML page, eliminating the need for a separate stylesheet."
Same for images and javascript (the 3 bullet points).

It is not the case or not anymore for https://github.com/404.

It appears to still be the case for https://github.com/500 (even if I see at least one external "error.js").

## Possible Solutions

Remove the reference to page 404 as an exemple of self contained error page. 
And/or maybe explain why it makes more sense to have self contained 500 errors (nginx can be the one to throw it, in that case the server and its assets are unavailable), whereas for 404, as far as what I've seen, your website / your assets are still working well and you've got just a dead link or something.

**Comment by pydanny** [comment]
🚢 🍨
