### ISSUE TITLE
Example 5.4 missing "ql" from end of "django.db.backends.postgres"

### ISSUE THREAD

**Issue by kc7wbq** [feldroy/two-scoops-of-django-3.x#99]
## Location within the Book

* Chapter: 5
* Section: 2
* Subsection: 1
* Example: 5.4

## Description 
It looks like the the last two characters of the `ENGINE` setting have been cut off. 

Currently: 
```
'ENGINE': 'django.db.backends.postgres',
```

But should be: 
```
'ENGINE': 'django.db.backends.postgresql',
```

With the current setting I get the error:
```
django.core.exceptions.ImproperlyConfigured: 'django.db.backends.postgres' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

## Your full name so we can provide accurate credit within the book
Keith Richards (All ready credited)

**Comment by kc7wbq** [comment]
The Two Scoops code is referenced in this stackoverflow question: https://stackoverflow.com/a/42077576/517724

**Comment by pydanny** [comment]
🚢 🍨
